language: vim

before_script: |
  git clone https://github.com/vim/vim
  cd vim
  # ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
  ./configure --with-features=huge
  make -j4
  sudo make install
  cd -

script: |
  which vim
  vim --version
  make test
